Fix #1
raulanatol/jest-coverage-comment-action pull request #2
Opened 2020-10-13 18:39 UTC by osedoe

2020-10-14 07:41 UTC, raulanatol requested changes

2020-10-14 07:41 UTC, raulanatol commented on src/utils.ts
> +      return '--changeSince=context.payload.pull_request.base_ref';
You need to check if is a pull_request action first.

```suggestion
      return `--changeSince=${context.payload.pull_request.base_ref}`;
```

2020-10-14 07:41 UTC, raulanatol commented on src/utils.ts
> +  const param = getInput('only-changes');
I think that can be better if we use here a wrapper as `getBooleanInput`

2020-10-14 07:41 UTC, raulanatol commented on src/utils.ts
> +  const changeSinceParam = generateChangeSinceParam();
We should need to check if the 'changeSince' parameter already exists in the `jest-command` input first.

2020-10-14 08:05 UTC, osedoe commented
I'll get to it this evening. Thx!

2020-10-19 07:58 UTC, raulanatol commented on src/utils.ts
> +
```suggestion
if (!param) {
   return '';
}
```

2020-10-19 08:00 UTC, raulanatol requested changes

2020-10-19 08:00 UTC, raulanatol commented on src/utils.ts
> +  }
```suggestion

```

2020-10-19 08:00 UTC, raulanatol commented on src/utils.ts
> +  if (!param || baseCommand.includes('changeSince')) {
```suggestion
  if (baseCommand.includes('changeSince')) {
```

2020-10-19 08:00 UTC, raulanatol commented on src/utils.ts
> +  if (param && context.payload.pull_request?.base_ref) {
```suggestion
  if (context.payload.pull_request?.base_ref) {
```

2020-10-19 12:27 UTC, raulanatol approved these changes

2020-10-19 12:27 UTC, merged